name: Create and Manage EC2 Instance

on:
  workflow_dispatch:

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Launch EC2 instance
      id: ec2
      uses: truemark/aws-ec2-run-instance-action@v5
      with:
        image-id: "ami-0cc1bbfc81dd6bc6d"
        region: "eu-west-2a"
        instance-type: "t2.micro"
        security-group-id: "sg-04d6e6013db1e2981"
        subnet-id: "subnet-0b75b6d6e9b59a5bd"
        instance-shutdown-behavior: terminate
        user-data: |
          #!/bin/sh
          echo "Running command on FreeBSD instance"
          # Add your command here
          echo "Hello from FreeBSD" > /tmp/hello.txt

    - name: Wait for instance to be ready
      run: |
        INSTANCE_ID=$(echo "${{ steps.ec2.outputs.instance-id }}")
        aws ec2 wait instance-status-ok --instance-ids $INSTANCE_ID

    - name: Execute command on EC2 instance
      run: |
        INSTANCE_ID=$(echo "${{ steps.ec2.outputs.instance-id }}")
        aws ssm send-command --instance-ids $INSTANCE_ID --document-name "AWS-RunShellScript" --parameters commands="cat /tmp/hello.txt"

    - name: Terminate EC2 instance
      run: |
        INSTANCE_ID=$(echo "${{ steps.ec2.outputs.instance-id }}")
        aws ec2 terminate-instances --instance-ids $INSTANCE_ID
